<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Angband3D</AssemblyName>
    <RootNamespace>Angband3D.Desktop</RootNamespace>
    <ApplicationTitle>Angband 3D</ApplicationTitle>
    <Company>Angband3D</Company>
    <Product>Angband 3D</Product>
    <Version>1.2.0</Version>
    <FileVersion>1.2.0.0</FileVersion>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <NoWarn>MSB3277</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3485.44" />
  </ItemGroup>
</Project>
